### ISSUE TITLE
Leaner Personas

### ISSUE THREAD

**Issue by njr0** [gvwilson/11-techbook#2]
I think you'll almost certainly disagree with this, but I'll say it anyway.

A lot of people advocate, as you do, writing for a very well-defined group of readers. And it seems like common sense. But I don't really agree with it. I agree that if you write something that assumes some particular knowledge, it's good to state and know that; but beyond that, I think it can do as much harm as good. People are complex and have weird mixes of experiences and aptitudes and interests, and I think the job of a writier is to lay out the information in as clear and accessible a way as possible, without making too many assumptions about the reader. Even if the reader does fit the writer's experiences or broad assumptions, it doesn't mean they'll necessarily us the same language, or think about things the same way, so some of the benefit of introductory material in an advanced books isn't so much to allow novices to learn at breakneck speed as to allow the writer to explain how (s)he works and thinks about things; and that can be extremely useful.

Anyway, as I say, you won't agree with this, and my opinion is definitely a minority one; but I think assuming a particular reader can be arrogant and destructive.

**Comment by gvwilson** [comment]
I'm sorry you find the practice arrogant and destructive - I think it has served me well.

**Comment by gvwilson** [comment]
I think "arrogant and destructuve" is rather strong - I think the practice has served me well over the years.

**Comment by njr0** [comment]
Like I say, it's minority opinion; and I'm sure it has. Hopefully the other one is more useful to you.
